name: notes
description: A new Flutter application.
version: 2.1.1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.0.0
  path_provider: ^1.3.1
  intl: ^0.16.1
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  meta: ^1.1.6
  equatable: ^1.0.2
  package_info: ^0.4.3
  pdf: ^1.11.0
  permission_handler: ^5.0.1+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/splash.png
    - images/rajputvarun591.jpg
    -
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Raleway-Medium
      fonts:
        - asset: fonts/Raleway-Medium.ttf
